#configure spring
spring:
  main.show_banner: false
  thymeleaf.cache: false
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/samiramysqldb?createDatabaseIfNotExist=true
    username: root
# JPA properties
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
    # Show or not log for each sql query
    show-sql: true
    database: mysql
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
# Logging
logging:
  file: logs/myapp.log
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.smr: DEBUG
    org.springframework: INFO
    org.hibernate: INFO    
#configure the server
server:
  port: 8888
